### ISSUE TITLE
Is there any config with Redis needed?

### ISSUE THREAD

**Issue by wznmickey** [mashirozx/feditool#1]
I use docker to deploy.
The related config is 
```
[redis]
; Redis server
; redis[s]://[[username][:password]@][host][:port][/db-number]
; url='redis://127.0.0.1:6379'
; 如果你用 docker compose 请使用下面这条
; If you are using docker compose, use below
url='redis://redis:6379'
```
The time I set is `cron='*/10 * * * * *'`
When running the project, it always has `Feed is processing, skip:`, this message comes from the part with Redis. Is it normal for the first start?

**Comment by mashirozx** [comment]
*/10 * * * * * means every 10 seconds. It might be too short for handling a new RSS feed. 

If it shows this at the first cron run turn, it's might because the program was not correctly killed before, and the process lock was not removed after that. To fix this mistake, please clear your redis data or shitch to a new redis db pool before restarting the service.

**Comment by wznmickey** [comment]
Thanks. I change to every 1 minute and shift ro a new redis db and it solved.
